# Slave Node Definitions - Auto-generated by Terraform

%{ for slave in slaves ~}
define host {
    use                     linux-server
    host_name               slave-${slave.index}
    alias                   Slave Node ${slave.index}
    address                 ${slave.ip_address}
    check_command           check_nrpe
    max_check_attempts      5
    check_period            24x7
    notification_interval   30
    notification_period     24x7
}

define service {
    use                     generic-service
    host_name               slave-${slave.index}
    service_description     CPU Load
    check_command           check_nrpe!check_load
    max_check_attempts      4
    check_interval          5
    retry_interval          1
    notification_interval   30
}

define service {
    use                     generic-service
    host_name               slave-${slave.index}
    service_description     Disk Usage
    check_command           check_nrpe!check_disk
    max_check_attempts      4
    check_interval          5
    retry_interval          1
}

define service {
    use                     generic-service
    host_name               slave-${slave.index}
    service_description     Memory Usage
    check_command           check_nrpe!check_mem
    max_check_attempts      4
    check_interval          5
    retry_interval          1
}

%{ endfor ~}
